# Generated by Django 3.1.1 on 2020-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offerpercentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
